name: Dialogflow CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup NodeJs 8
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: Install dialogflow-cli
      run: npm install dialogflow-cli -g
    - run: echo $credentials_json  > ./credentials.json
      env:
        credentials_json: ${{ secrets.CREDENTIALS_JSON }}
    - run: dialogflow-cli import --credentials ./credentials.json .
      env:
        CI: true

    - name: Setup NodeJs 13
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
        registry-url: 'https://npm.pkg.github.com'
        scope: '@grouch-trash-service'
    - name: Install firebase-tools
      run: npm install firebase-tools -g
    - name: Install
      run: npm install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Test
      run: npm test
    - name: Run local cucumber tests
      run: |
        echo $runtime_config > .runtimeconfig.json
        firebase emulators:exec "npm run cucumber"
      env:
        runtime_config: ${{ secrets.RUNTIME_CONFIG }}
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Check Sonar Status
      run: |
        status=$(curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=matthew-js-porter_oscar-google-action)
        echo $status | jq '.'
        status=$(echo $status | jq '.projectStatus.status')
        test '"OK"' = $status
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --file=functions/package-lock.json --severity-threshold=high --policy-path=.snyk
    - name: Replace .npmrc with token
      run: sed -i.bak "s/\${NODE_AUTH_TOKEN}/${NODE_AUTH_TOKEN}/g" functions/.npmrc
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: update Firebase env
      run: firebase functions:config:set api.url="https://d9lz2a1tq2.execute-api.us-east-1.amazonaws.com/Prod" api.key="$api_key"
      env:
        api_key: ${{ secrets.AWS_API_KEY }}

    - name: Deploy Firebase
      run: firebase deploy --token "$firebase_token"
      env:
        firebase_token: ${{ secrets.FIREBASE_TOKEN }}
        CI: true
    - name: Run Cucumber Tests
      run: npm run cucumber
      env:
        NODE_ENV: production
