name: Dialogflow CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy Dialogflow
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - run: npm install dialogflow-cli -g
    - run: echo $credentials_json  > ./credentials.json
      env:
        credentials_json: ${{ secrets.CREDENTIALS_JSON }}
    - run: dialogflow-cli import --credentials ./credentials.json .
      env:
        CI: true

    - name: Deploy Firebase
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - run: npm install firebase-tools -g
    - run: npm install
    - run: npm test
    - run: firebase deploy --token "$firebase_token"
      env:
        firebase_token: ${{ secrets.FIREBASE_TOKEN }}
        CI: true
